# https://docs.travis-ci.com/user/languages/android
language: android
android:
    components:
        # https://github.com/travis-ci/travis-ci/issues/5036
        - tools
        - platform-tools
        - build-tools-23.0.3
        - android-23
        - extra-google-m2repository
        - extra-android-m2repository

env:
    # http://stackoverflow.com/questions/35634437
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
